builds:
- binary: cloudcost
  main: ./
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  flags:
  - -mod=vendor

release:
  prerelease: auto

universal_binaries:
- replace: true

brews:
- name: cloudcost
  homepage: "https://github.com/muandane/homebrew-gitmoji"
  tap:
    owner: muandane
    name: homebrew-gitmoji
  commit_author:
    name: muandane
    email: zmoualhi@outlook.com

checksum:
  name_template: 'checksums.txt'
