name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21.3'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
          workdir: src
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: cloudcost
          formula-path: Formula/cloudcost.rb
          homebrew-tap: muandane/homebrew-tap
        env:
          COMMITTER_TOKEN:  ${{ secrets.COMMITTER_TOKEN }}